import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "../components/sidebar/sidebar";
import Providers from "../states/providers";
import {
  PostModalDialog,
  PostModalDialogTrigger,
  PostModalDialogContent,
  PostModalDialogHeader,
  PostModalDialogFooter,
  PostModalDialogTitle,
  PostModalDialogDescription,
  PostModalDialogAction,
  PostModalDialogCancel,
} from "../components/feed/PostModal"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
      <html lang="en">
        <body className="nanumbarungothic">
          <Providers>
            
            {children}
            <Sidebar/>
          </Providers>
        </body>
      </html>
    
  );
}


